version: '3.8'

services:
  zhgi_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: zhgi_user
      POSTGRES_PASSWORD: zhgi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  zhgi_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zhgi_postgres
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://zhgi_user:zhgi_password@zhgi_postgres:5432/zhgi_user

volumes:
  postgres_data:
